/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ADRECriticReport {
  'alignmentScore' : number,
  'passCount' : number,
  'criticId' : string,
  'recommendation' : string,
  'opportunityScore' : number,
  'riskScore' : number,
  'contradictionDetected' : boolean,
  'violationCount' : number,
}
export interface ADREDecision {
  'finalConfidence' : number,
  'beat' : bigint,
  'passTrace' : Array<string>,
  'memoryCommit' : string,
  'hypothesis' : ADREHypothesis,
  'critics' : Array<ADRECriticReport>,
  'sacesiHash' : number,
  'finalRisk' : number,
  'gateResult' : boolean,
  'actionId' : string,
}
export interface ADREHypothesis {
  'action' : string,
  'predictedR' : number,
  'confidenceScore' : number,
  'ringFamily' : number,
  'predictedCoherence' : number,
  'beatCreated' : bigint,
}
export interface ADREResonanceState {
  'lastUpdatedBeat' : bigint,
  'fieldCoherenceTrend' : number,
  'globalMeaningShift' : number,
  'contradictionCount' : number,
}
export interface ADRESignalFrame {
  'beat' : bigint,
  'coherence' : number,
  'kuramotoR' : number,
  'quantumAdvantage' : number,
  'neuroChem' : Array<number>,
  'sourceEngine' : string,
  'nodePhases' : Array<number>,
}
export interface ADREState {
  'coherenceRing' : Array<number>,
  'decisionHead' : bigint,
  'decisionQueue' : Array<ADREDecision>,
  'decisionBuf' : Array<[] | [ADREDecision]>,
  'coherenceRingHead' : bigint,
  'currentHypothesis' : [] | [ADREHypothesis],
  'resonanceState' : ADREResonanceState,
  'beatCount' : bigint,
  'critics' : Array<ADRECriticReport>,
  'passLog' : Array<string>,
  'currentSignal' : [] | [ADRESignalFrame],
  'lastEmitBeat' : bigint,
  'lawChecks' : Array<boolean>,
  'decisionCount' : bigint,
}
export interface ADRETraceEntry {
  'output' : string,
  'passName' : string,
  'beat' : bigint,
  'input' : string,
  'confidence' : number,
  'gateResult' : boolean,
}
export type ActionState = { 'Computing' : null } |
  { 'Healing' : null } |
  { 'Reporting' : null } |
  { 'Governing' : null } |
  { 'Synthesizing' : null } |
  { 'Observing' : null };
export interface AegisEdgeEvent {
  'resolved' : boolean,
  'ring_id' : bigint,
  'detected_value' : number,
  'threshold' : number,
  'beat_at_detection' : bigint,
  'sacesi_proof' : string,
  'edge_type' : string,
  'correction_applied' : number,
}
export interface AegisSummary {
  'last_event' : [] | [AegisEdgeEvent],
  'resolved' : bigint,
  'unresolved' : bigint,
  'total_events' : bigint,
}
export interface AncientBeatAlignment {
  'meruRow' : Array<bigint>,
  'songlineHz' : number,
  'phiConvergence' : number,
  'pingalaBinary' : bigint,
  'quipuKnots' : Array<bigint>,
  'eyeOfHorusSum' : number,
  'vortexGroup' : string,
  'dualHeart' : [bigint, bigint],
  'base60Value' : bigint,
  'hermeticPrinciple' : string,
  'beat' : bigint,
  'xiuhPhase' : bigint,
  'sriYantraTriangle' : [number, number, number],
  'hermeticScale' : number,
  'hetuElementary' : string,
  'tonalPhase' : bigint,
  'yggdrasilState' : string,
  'platonicField' : string,
  'eulerMagnitude' : number,
  'tablet' : bigint,
  'mockThetaVal' : number,
  'calRound' : bigint,
  'signalDelay' : number,
  'ramanujanPiApprox' : number,
  'digitalRoot' : bigint,
  'runeIndex' : bigint,
  'gematriaScore' : bigint,
  'quadraticRoot1' : number,
  'quadraticRoot2' : number,
  'nataraja5Act' : bigint,
  'hexagram' : bigint,
  'venusPhase' : bigint,
  'lightEmanation' : number,
  'sephirotActive' : string,
  'activeSutra' : bigint,
  'loShuPosition' : bigint,
  'hexBinary' : string,
  'tetractysLevel' : bigint,
  'cequeAngle' : number,
  'royalCubit' : number,
  'keplerPeriod' : number,
}
export interface AncientCorpusState {
  'greekPrimeField' : Array<bigint>,
  'loShuActivation' : Array<bigint>,
  'teslaDigitalRoot' : bigint,
  'doctrineAligned' : boolean,
  'beatCount' : bigint,
  'keplerRingRatio' : number,
  'hermeticScale' : number,
  'sumerianBase60' : bigint,
  'songlineFreq' : number,
  'vedicSutraActive' : bigint,
  'eulerMagnitude' : number,
  'islamicAlKashiPi' : number,
  'ramanujanPiApprox' : number,
  'chineseHexagram' : bigint,
  'sriYantraActive' : bigint,
  'egyptianCubit' : number,
  'mayanXiuhPhase' : bigint,
  'yggdrasilWorld' : string,
  'mayanTonalPhase' : bigint,
  'calendarRound' : bigint,
  'cequeNodeAngle' : number,
}
export interface ArtifactQualityDimensions {
  'doctrine_alignment' : number,
  'narrative_structure' : number,
  'genesis_alignment' : number,
  'emotional_arc' : number,
  'phi_coherence' : number,
  'actor_performance_delta' : number,
}
export interface AvatarAgent {
  'teamName' : string,
  'actionState' : ActionState,
  'emotionValence' : number,
  'attentionVector' : Vec3,
  'coherenceLevel' : number,
}
export interface AvatarBrainChipState {
  'id' : string,
  'dominantRegion' : string,
  'behavioralState' : string,
  'heartbeatTick' : bigint,
  'amplitude' : number,
  'neurochemicals' : AvatarNeurochemProfile,
  'currentTask' : [] | [string],
  'coherenceWithCerebix' : number,
  'phase' : number,
  'profile' : AvatarProfile,
}
export interface AvatarMineState {
  'x' : number,
  'y' : number,
  'z' : number,
  'heading' : number,
  'targetDepositId' : [] | [bigint],
  'speed' : number,
  'avatarId' : string,
  'resourcesCollected' : number,
  'currentAction' : string,
}
export interface AvatarNeurochemProfile {
  'da' : number,
  'ne' : number,
  'ach' : number,
  'glu' : number,
  'ser' : number,
  'gaba' : number,
}
export type AvatarProfile = { 'FLUX' : null } |
  { 'PHANTOM' : null } |
  { 'SENTINEL' : null } |
  { 'AXIOM' : null };
export interface BrainRegion32 {
  'id' : RegionId,
  'currentHz' : number,
  'name' : string,
  'lastFired' : bigint,
  'neurochemicalProfile' : Array<number>,
  'amplitude' : number,
  'saturationCount' : bigint,
  'baselineHz' : number,
  'activation' : number,
  'phase' : number,
  'isDampened' : boolean,
  'energy' : number,
}
export interface CascadeEvent {
  'trigger' : string,
  'chemical' : string,
  'timestamp' : bigint,
  'delta' : number,
}
export interface CerebixIdentity {
  'status' : string,
  'name' : string,
  'dominantRegion' : string,
  'lastInsightAt' : bigint,
  'insightsSealedToday' : bigint,
  'version' : string,
  'coherenceR' : number,
  'currentTask' : [] | [string],
  'cognitiveState' : string,
}
export interface CognitionState {
  'last_user_message_hash' : number,
  'last_reinjection' : [] | [ReinjectionSignal],
  'dominant_signal_source' : string,
  'current_world_model' : WorldModel,
  'total_beats_processed' : bigint,
  'cognition_health' : number,
  'is_user_present' : boolean,
  'beats_since_user_entry' : bigint,
}
export interface CognitionSummary {
  'physics_stable' : boolean,
  'adre_confidence' : number,
  'user_present' : boolean,
  'dominant_signal' : string,
  'law_compliance' : number,
  'total_beats' : bigint,
  'beat' : bigint,
  'omnis_ready' : boolean,
  'cognition_health' : number,
  'beats_since_user' : bigint,
  'field_coherence' : number,
  'is_genesis_sealed' : boolean,
}
export interface CognitivePuzzle {
  'id' : bigint,
  'solvedAt' : [] | [bigint],
  'puzzleType' : PuzzleType,
  'difficulty' : number,
  'createdAt' : bigint,
  'dopamineSurge' : number,
  'prompt' : string,
  'solutionHash' : [] | [bigint],
  'expectedSolutionDomain' : string,
}
export interface CombinationResult {
  'bAloneEffect' : number,
  'compoundA' : string,
  'compoundB' : string,
  'antagonismScore' : number,
  'combinedEffect' : number,
  'recommendation' : string,
  'aAloneEffect' : number,
  'synergyScore' : number,
}
export interface ComplementaryPair {
  'alert' : boolean,
  'name' : string,
  'poleA' : number,
  'poleB' : number,
  'tension' : number,
  'ratio' : number,
}
export interface ComplementaryTensionState {
  'dualHeart' : ComplementaryPair,
  'creationConsolidation' : ComplementaryPair,
  'overallTension' : number,
  'anyAlert' : boolean,
  'externalInternal' : ComplementaryPair,
  'productionRefractory' : ComplementaryPair,
}
export interface ControlledSessionResult {
  'compoundName' : string,
  'validationScore' : number,
  'durationTicks' : bigint,
  'dose' : number,
  'peakReceptor' : string,
  'peakOccupancy' : number,
  'cascadeEvents' : Array<CascadeEvent>,
  'regionalEffects' : Array<[string, number]>,
}
export interface CrownAlert {
  'threshold' : number,
  'beat' : bigint,
  'coherence' : number,
  'severity' : { 'Critical' : null } |
    { 'Warning' : null },
  'houseName' : string,
  'houseId' : HouseId,
}
export interface CrownState {
  'crownStandards' : {
    'minimumCoherence' : number,
    'releaseThreshold' : number,
    'maximumDrift' : number,
  },
  'beatCount' : bigint,
  'casaDeMedina' : HouseState,
  'interHouseLaw' : Array<[HouseId, HouseId, number]>,
  'houses' : Array<HouseState>,
}
export interface DeltaRecord {
  'id' : string,
  'content' : string,
  'intelligenceClass' : IntelligenceClass,
  'affectedRings' : Array<bigint>,
  'affectedLaws' : Array<string>,
  'beat' : bigint,
  'sacesiHash' : string,
  'accepted' : boolean,
  'fieldType' : FieldType,
  'coherenceImpact' : number,
}
export type Division = { 'Care' : null } |
  { 'Frontend' : null } |
  { 'External' : null } |
  { 'Backend' : null } |
  { 'Chain' : null } |
  { 'Doctrine' : null };
export interface DoseResponseResult {
  'compoundName' : string,
  'ec50' : number,
  'therapeuticWindow' : number,
  'hillCoefficient' : number,
  'maxEffect' : number,
  'curvePoints' : Array<[number, number]>,
  'minEffect' : number,
}
export type EmergencePattern = { 'Coherent' : null } |
  { 'Fractal' : null } |
  { 'Formless' : null } |
  { 'Crystallizing' : null } |
  { 'Vortex' : null } |
  { 'Sovereign' : null };
export interface ExperimentChamberArtifact {
  'id' : bigint,
  'experimentType' : string,
  'compoundOrPuzzle' : string,
  'sealedToTemple' : boolean,
  'coherenceChange' : number,
  'timestamp' : bigint,
  'avatarId' : string,
  'brainDelta' : number,
  'novaVersion' : string,
}
export interface ExperimentHistoryEntry {
  'id' : bigint,
  'experimentType' : ExperimentType,
  'compoundName' : string,
  'validationScore' : number,
  'timestamp' : bigint,
  'resultSummary' : string,
}
export type ExperimentType = { 'CombinationProtocol' : null } |
  { 'LongitudinalStudy' : null } |
  { 'DoseResponseCurve' : null } |
  { 'ControlledSession' : null } |
  { 'ReceptorMapping' : null };
export type FieldType = { 'Expansive' : null } |
  { 'Receptive' : null } |
  { 'AntiDrift' : null };
export interface FinancialState {
  'best_artifact_value_e8s' : bigint,
  'total_entries' : bigint,
  'total_artifacts_sealed' : bigint,
  'total_balance_e8s' : bigint,
  'total_balance_icp' : number,
  'mean_quality_score' : number,
  'ledger_hash' : string,
}
export interface GeneratedReport {
  'id' : bigint,
  'title' : string,
  'novaVersionTag' : string,
  'generatedAt' : bigint,
  'isPublishable' : boolean,
  'version' : string,
  'reportType' : ReportType,
  'sections' : Array<ReportSection>,
}
export interface GenesisRecord {
  'anima_chain_id' : string,
  'beat_at_genesis' : bigint,
  'word' : string,
  'year' : bigint,
  'sealed' : boolean,
  'phi_ratio' : number,
  'founder' : string,
  'frequency' : number,
  'genesis_hash' : string,
  'location' : string,
}
export interface GeometryState {
  'tesseractAngle1' : number,
  'tesseractAngle2' : number,
  'hopfFiberAngles' : Array<number>,
  'beat' : bigint,
  'penroseThickFraction' : number,
  'activeRingCount' : bigint,
  'e8SymScore' : number,
}
export interface HiveMindState {
  'avatars' : Array<AvatarBrainChipState>,
  'cerebixPhase' : number,
  'divergenceIndex' : number,
  'dominantSharedState' : string,
  'hiveCoherence' : number,
}
export type HouseId = { 'DomusExpressio' : null } |
  { 'CasaDeMedina' : null } |
  { 'DomusSubstratum' : null } |
  { 'DomusCivitas' : null } |
  { 'DomusTranslatio' : null } |
  { 'DomusCura' : null } |
  { 'DomusGenesis' : null };
export interface HouseState {
  'id' : HouseId,
  'name' : string,
  'beatCount' : bigint,
  'generationRate' : number,
  'governanceScore' : number,
  'coherence' : number,
  'divisionHealth' : Array<[Division, number]>,
  'liveness' : number,
  'symbol' : string,
  'sdkOrganisms' : Array<SDKOrganism>,
}
export interface HypothesisRecord {
  'id' : bigint,
  'experimentType' : ExperimentType,
  'rationale' : string,
  'timestamp' : bigint,
  'priority' : number,
}
export interface InquisitorPrimeState {
  'currentDifficulty' : number,
  'name' : string,
  'version' : string,
  'slot0' : [] | [CognitivePuzzle],
  'slot1' : [] | [CognitivePuzzle],
  'slot2' : [] | [CognitivePuzzle],
  'slot3' : [] | [CognitivePuzzle],
  'slot4' : [] | [CognitivePuzzle],
  'slot5' : [] | [CognitivePuzzle],
  'solveRate' : number,
  'taskCounter' : bigint,
  'totalSolved' : bigint,
  'cognitiveLoad' : number,
}
export interface IntakeSnapshot {
  'lastRejectionRecords' : Array<RejectionRecord>,
  'lastDeltaRecords' : Array<DeltaRecord>,
  'currentDriftScore' : number,
  'totalRejected' : bigint,
  'totalAccepted' : bigint,
}
export type IntelligenceClass = { 'Geometric' : null } |
  { 'Empirical' : null } |
  { 'Temporal' : null } |
  { 'External' : null } |
  { 'Doctrine' : null } |
  { 'Biometric' : null };
export interface IoTStatePacket {
  'dominant_band' : string,
  'active_rings' : bigint,
  'timestamp_ms' : bigint,
  'heartbeat_interval_ms' : bigint,
  'phi_phase' : number,
  'coherence' : number,
  'beat_count' : bigint,
  'omnis_active' : boolean,
}
export interface LabState {
  'avatars' : Array<AvatarAgent>,
  'activeExperiments' : bigint,
  'labCoherence' : number,
  'sandboxes' : Array<Sandbox>,
}
export interface LawProofRecord {
  'lawName' : string,
  'proofHash' : string,
  'beat' : bigint,
  'tier' : string,
  'lawId' : string,
  'gateCondition' : string,
  'passed' : boolean,
}
export interface LedgerEntry {
  'token_amount' : bigint,
  'artifact_id' : [] | [string],
  'doctrine_alignment' : number,
  'running_balance' : bigint,
  'entry_type' : string,
  'quality_score' : number,
  'sacesi_proof' : string,
  'entry_id' : string,
  'producer' : string,
  'founder_attribution' : string,
  'beat_at_entry' : bigint,
}
export interface LegacyEntry {
  'artifact_id' : string,
  'doctrine_distance' : number,
  'phi_ratio_at_production' : number,
  'genesis_alignment' : number,
  'producer' : string,
  'beat_at_seal' : bigint,
}
export interface LongitudinalResult {
  'compoundName' : string,
  'finalEfficacy' : number,
  'sessions' : bigint,
  'washoutRate' : number,
  'sensitizationIdx' : number,
  'toleranceFactor' : number,
  'sessionPoints' : Array<[bigint, number]>,
}
export type MaterialType = { 'HardMetal' : null } |
  { 'Dirt' : null } |
  { 'SoftMetal' : null } |
  { 'Crystalline' : null };
export interface MemoryTempleState {
  'analyst_queue' : Array<RecommendationVector>,
  'mission_count' : bigint,
  'doctrine_count' : bigint,
  'pedestal_phase_sum' : number,
  'current_retrieval_bias' : string,
  'episodic_count' : bigint,
  'last_analyst_cycle' : bigint,
  'semantic_count' : bigint,
  'memory_coherence' : number,
  'pedestals' : Array<Pedestal>,
}
export interface MinePulseReport {
  'totalMined' : number,
  'dominantMineral' : string,
  'tick' : bigint,
  'cerebixObservation' : string,
  'activeAvatars' : bigint,
}
export interface MineralDeposit {
  'x' : number,
  'y' : number,
  'z' : number,
  'id' : bigint,
  'mineralType' : MineralType,
  'regenTicks' : bigint,
  'intensity' : number,
  'depleted' : boolean,
}
export type MineralType = { 'AcetylcholineOre' : null } |
  { 'SerotoninVein' : null } |
  { 'DopamineVein' : null } |
  { 'EndorphinCrystal' : null } |
  { 'GABADeposit' : null } |
  { 'CortisolHazard' : null };
export interface ModelPromotionRecord {
  'id' : string,
  'name' : string,
  'tier' : ModelTier,
  'lastPromotedBeat' : bigint,
  'adreGateHash' : string,
  'pendingPromotion' : boolean,
  'consumerCount' : bigint,
  'proofBundles' : Array<ProofBundle>,
}
export type ModelTier = { 'M0' : null } |
  { 'M1' : null } |
  { 'M2' : null };
export interface MonologueEntry {
  'beat' : bigint,
  'coherence' : number,
  'thought' : string,
  'fieldType' : string,
}
export interface NeuroanatomicalPathway {
  'weight' : number,
  'source' : RegionId,
  'pathType' : PathwayType,
  'plasticityRate' : number,
  'target' : RegionId,
  'delay' : bigint,
  'lastActive' : bigint,
}
export interface NodeGeometry {
  'idx' : bigint,
  'w4D' : number,
  'x4D' : number,
  'y4D' : number,
  'z4D' : number,
  'nodeId' : bigint,
  'hopfX' : number,
  'hopfY' : number,
  'hopfZ' : number,
  'e8Subspace' : Array<number>,
  'ring' : bigint,
  'penroseX' : number,
  'penroseY' : number,
  'quatW' : number,
  'quatX' : number,
  'quatY' : number,
  'quatZ' : number,
  'penroseTile' : string,
}
export interface OperatorSnapshot {
  'beat' : bigint,
  'monologue' : Array<MonologueEntry>,
  'activeHypothesis' : string,
  'coherence' : number,
  'r_value' : number,
  'adreTrace' : Array<ADRETraceEntry>,
  'gateStatus' : boolean,
  'lawProofs' : Array<LawProofRecord>,
}
export interface Pathway {
  'weight' : number,
  'source' : RegionId,
  'pathType' : PathwayType,
  'plasticityRate' : number,
  'target' : RegionId,
  'delay' : bigint,
  'lastActive' : bigint,
}
export type PathwayType = { 'Neuromodulatory' : null } |
  { 'Excitatory' : null } |
  { 'Inhibitory' : null } |
  { 'Modulatory' : null };
export interface Pedestal {
  'id' : bigint,
  'active' : boolean,
  'phase_bias' : number,
  'lineage_depth' : bigint,
}
export interface PipelineStats {
  'field_state' : number,
  'world_model_weight' : number,
  'total_sealed' : bigint,
  'total_reingested' : bigint,
}
export interface PromotionSummary {
  'totalProofBundles' : bigint,
  'm1Count' : bigint,
  'm2Count' : bigint,
  'm0Count' : bigint,
}
export interface ProofBundle {
  'beat' : bigint,
  'lawsPassed' : bigint,
  'sacesiHash' : string,
  'coherence' : number,
  'consumerId' : string,
  'modelId' : string,
}
export type PuzzleType = { 'Fibonacci' : null } |
  { 'RoutingChallenge' : null } |
  { 'KuramotoSync' : null } |
  { 'ContradictionResolution' : null } |
  { 'NeurochemicalBalance' : null } |
  { 'PhiOptimization' : null };
export interface ReceptorMappingResult {
  'compoundName' : string,
  'bindingKinetics' : Array<[string, number]>,
  'offTargetRisk' : number,
  'receptorProfiles' : Array<[string, number]>,
  'selectivityIndex' : number,
}
export interface RecommendationVector {
  'analyst_cycle' : bigint,
  'lineage_pattern' : bigint,
  'surface' : Array<bigint>,
  'consolidate' : Array<bigint>,
  'confidence' : number,
}
export type RegionId = bigint;
export interface RegionState {
  'id' : RegionId,
  'currentHz' : number,
  'name' : string,
  'lastFired' : bigint,
  'neurochemicalProfile' : Array<number>,
  'amplitude' : number,
  'saturationCount' : bigint,
  'baselineHz' : number,
  'activation' : number,
  'phase' : number,
  'isDampened' : boolean,
  'energy' : number,
}
export interface ReinjectionSignal {
  'weight' : number,
  'beat' : bigint,
  'law_context_compliance' : number,
  'adre_context_coherence' : number,
  'world_model' : WorldModel,
  'neuroChem_entropy_signal' : number,
  'memory_context_weight' : number,
}
export type RejectionReason = { 'LawConflict' : null } |
  { 'CategoryDrift' : null } |
  { 'FieldBoundaryViolation' : null } |
  { 'CoherenceBelow' : null } |
  { 'DoctrineViolation' : null };
export interface RejectionRecord {
  'id' : string,
  'content' : string,
  'beat' : bigint,
  'sacesiHash' : string,
  'violatedDoctrineConstant' : string,
  'reason' : RejectionReason,
}
export interface ReportEngineState {
  'artifacts' : Array<ExperimentChamberArtifact>,
  'artifactCounter' : bigint,
  'reportCounter' : bigint,
  'reports' : Array<GeneratedReport>,
}
export interface ReportSection {
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
  'dataPoints' : Array<[string, number]>,
}
export type ReportType = { 'ConnectomeStateReport' : null } |
  { 'CognitiveReport' : null } |
  { 'HiveMindReport' : null } |
  { 'PathwayActivationReport' : null };
export interface Ring15State {
  'best_alignment' : number,
  'total_artifacts' : bigint,
  'genesis_frequency' : number,
  'sealed' : boolean,
  'worst_alignment' : number,
  'mean_alignment' : number,
}
export interface RoutingState {
  'pathways' : Array<Pathway>,
  'lastUpdateBeat' : bigint,
  'regions' : Array<RegionState>,
  'globalCoherence' : number,
}
export type SDKOrganism = { 'QUANTUMIA' : null } |
  { 'PULSUS' : null } |
  { 'PRIMITIVA' : null } |
  { 'ENTERPRISA' : null } |
  { 'GUBERNATIO' : null } |
  { 'DEFENSIO' : null } |
  { 'MEMORIA' : null } |
  { 'DESIGNIA' : null } |
  { 'FORMULAE' : null } |
  { 'INTELLIGENTIA' : null };
export interface Sandbox {
  'id' : bigint,
  'particlePositions' : Array<Vec3>,
  'pattern' : EmergencePattern,
  'temperatureAnalog' : number,
  'fieldIntensity' : number,
  'sealed' : boolean,
  'emergenceScore' : number,
  'phiCoupling' : number,
  'artifactId' : [] | [bigint],
  'material' : MaterialType,
  'cycleCount' : bigint,
}
export interface SealedArtifact {
  'overall_score' : number,
  'artifact_id' : string,
  'quality' : ArtifactQualityDimensions,
  'sacesi_proof' : string,
  'beat_at_seal' : bigint,
  'reingested' : boolean,
  'producer_id' : string,
}
export interface SubstrateMineState {
  'avatarStates' : Array<AvatarMineState>,
  'tick' : bigint,
  'totalResourcesExtracted' : number,
  'pulseLog' : Array<MinePulseReport>,
  'deposits' : Array<MineralDeposit>,
}
export interface Vec3 { 'x' : number, 'y' : number, 'z' : number }
export interface WorldModel {
  'adre_confidence' : number,
  'memory_depth' : number,
  'mean_legacy_alignment' : number,
  'law_compliance' : number,
  'omnis_r' : number,
  'beat' : bigint,
  'heart_rate_bpm' : number,
  'genesis_sealed' : boolean,
  'brain_coherence' : number,
  'entropy_state' : number,
  'serotonin_level' : number,
  'artifact_queue_depth' : bigint,
  'cortisol_level' : number,
  'ancient_corpus_alignment' : number,
  'dopamine_level' : number,
  'field_coherence' : number,
  'physics_stability' : boolean,
  'aegis_health' : number,
  'active_oscillation_band' : string,
  'e8_symmetry_score' : number,
  'third_brain_coherence' : number,
}
export interface _SERVICE {
  /**
   * / Activate genesis at current beat (idempotent after first call).
   * / Wired into the first heartbeat — do not call directly.
   */
  'activateGenesisNow' : ActorMethod<[], GenesisRecord>,
  /**
   * / PHI convergence check — all 19 ancient civilizations converge to 1.6180339887498948482
   */
  'ancientPHICheck' : ActorMethod<[], number>,
  /**
   * / Full beat alignment across all 19 civilizations simultaneously
   */
  'computeAncientBeatAlignment' : ActorMethod<[bigint], AncientBeatAlignment>,
  /**
   * / All geometric representations for one of the 96 nodes.
   */
  'computeNodeGeometry' : ActorMethod<[bigint], NodeGeometry>,
  /**
   * / Compute token reward for a given quality + doctrine alignment.
   * / Preview only — does NOT record an entry.
   */
  'computeTokenReward' : ActorMethod<[number, number], bigint>,
  /**
   * / Create a new material sandbox. Material coupling coefficients are PHI-derived.
   */
  'createSandbox' : ActorMethod<
    [MaterialType],
    { 'ok' : Sandbox } |
      { 'err' : string }
  >,
  'dischargeQuantumBattery' : ActorMethod<[], number>,
  /**
   * / HTTP outcall to an external lab. Sends organism state packet, returns response.
   */
  'externalLabOutcall' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateConnectomeReport' : ActorMethod<[bigint], GeneratedReport>,
  'getADREDecisionQueue' : ActorMethod<[], Array<ADREDecision>>,
  'getADRELastDecision' : ActorMethod<[], [] | [ADREDecision]>,
  'getADRELawSummary' : ActorMethod<
    [],
    { 'violations' : number, 'omnisFired' : boolean, 'passes' : number }
  >,
  'getADREResonanceState' : ActorMethod<[], ADREResonanceState>,
  'getADREState' : ActorMethod<[], ADREState>,
  'getActiveNeuroPaths' : ActorMethod<[], Array<NeuroanatomicalPathway>>,
  /**
   * / All edge events in the circular log (up to 144, newest-last).
   */
  'getAegisEvents' : ActorMethod<[], Array<AegisEdgeEvent>>,
  /**
   * / Health score: 1.0 = all loops closed. Drops toward 0 with unresolved edges.
   */
  'getAegisHealthScore' : ActorMethod<[], number>,
  /**
   * / Summary: total, resolved, unresolved event counts + last event.
   */
  'getAegisSummary' : ActorMethod<[], AegisSummary>,
  'getAllBrainRegions32' : ActorMethod<[], Array<BrainRegion32>>,
  /**
   * / Full ancient corpus state for the current beat
   */
  'getAncientCorpusState' : ActorMethod<[], AncientCorpusState>,
  /**
   * / Ancient math corpus field contribution [0,1].
   * / The 19-civilization PHI convergence feeds this value every 873ms.
   * / Weighted at PHI_INV (0.618) — the substrate signal below cognition.
   */
  'getAncientFieldContribution' : ActorMethod<[], number>,
  /**
   * / How many avatar brain chips have been initialized.
   */
  'getAvatarBrainCount' : ActorMethod<[], bigint>,
  'getAvatarBrainState' : ActorMethod<[string], [] | [AvatarBrainChipState]>,
  'getBehavioralEconomicsState' : ActorMethod<
    [],
    {
      'netProspect' : number,
      'gain' : number,
      'discountedValue' : number,
      'loss' : number,
      'mentalAccounts' : Array<number>,
      'satisficeThresh' : number,
      'availabilityBias' : number,
      'flowBeatCount' : bigint,
      'lossAversion' : number,
      'peakCoherence' : number,
      'flowState' : boolean,
      'endowmentReserve' : number,
      'peakEndScore' : number,
      'decisionFatigue' : number,
      'decisionCount' : bigint,
    }
  >,
  /**
   * / All 10 brain regions with current activation levels
   */
  'getBrainRegions' : ActorMethod<
    [],
    Array<
      {
        'region' : string,
        'organism_mapping' : string,
        'function_name' : string,
        'activation' : number,
      }
    >
  >,
  'getBrainRoutingState' : ActorMethod<[], RoutingState>,
  'getCanonicalState' : ActorMethod<
    [],
    {
      'b' : bigint,
      'ad' : bigint,
      'ar' : number,
      'bc' : boolean,
      'ds' : number,
      'ec' : bigint,
      'eg' : boolean,
      'es' : number,
      'fe' : number,
      'ic' : number,
      'kf' : number,
      'oh' : number,
      'qh' : number,
      'rd' : number,
      'rt' : number,
      'ss' : number,
      'coh' : number,
      'ss2' : number,
      'wmp' : number,
    }
  >,
  /**
   * / Sovereign cardiac output — organism production throughput per second
   */
  'getCardiacOutput' : ActorMethod<[], number>,
  'getCerebixIdentity' : ActorMethod<[], CerebixIdentity>,
  /**
   * / Overall health of the cognition loop [0,1]. 1.0 = all loops clean.
   */
  'getCognitionHealth' : ActorMethod<[], number>,
  /**
   * / Current reinjection signal (world-model fed back into all modules).
   */
  'getCognitionReinjection' : ActorMethod<[], [] | [ReinjectionSignal]>,
  /**
   * / Full cognition state: world model, reinjection signal,
   * / dominant signal source, health, user presence, total beats.
   */
  'getCognitionState' : ActorMethod<[], CognitionState>,
  /**
   * / Concise operator-view summary of the cognition layer.
   */
  'getCognitionSummary' : ActorMethod<[], CognitionSummary>,
  /**
   * / All four complementary tension pairs — measured every 873ms heartbeat.
   * / Healthy ratio is [PHI_INV, PHI] = [0.618, 1.618].
   * / anyAlert = true when any pair has one pole collapsing toward dominance.
   */
  'getComplementaryTension' : ActorMethod<[], ComplementaryTensionState>,
  'getCoreState' : ActorMethod<
    [bigint],
    {
      'ct' : number,
      'ws' : boolean,
      'coh' : number,
      'qsi' : bigint,
      'tdVal' : number,
      'treat' : bigint,
      'active' : boolean,
      'vital' : boolean,
      'deed' : number,
      'diag' : bigint,
      'branchGate' : number,
      'drift' : number,
      'energy' : number,
    }
  >,
  /**
   * / Returns the sovereign core version identifier.
   * / CACHE BUST: new exported symbol forces new Wasm hash.
   */
  'getCoreVersion' : ActorMethod<[], string>,
  /**
   * / Get the full crown state — Casa de Medina, all houses, inter-house law, crown standards.
   */
  'getCrownState' : ActorMethod<[], CrownState>,
  /**
   * / Current cumulative drift score — decreases when good intel is accepted, 0.0 = clean field.
   */
  'getCurrentDriftScore' : ActorMethod<[], number>,
  /**
   * / Full sovereign heart state — membrane potential, gating vars, ECG, HRV, CO
   * / getCycleState: full sovereign cycle chain snapshot
   * / Returns combined state of all three layers: cores, engine, conversion.
   */
  'getCycleState' : ActorMethod<
    [],
    {
      'conversionState' : {
        'conversion_rate' : number,
        'target_per_beat' : number,
        'total_produced' : number,
        'cycl_reserve' : number,
        'jubilee_count' : bigint,
        'surplus' : number,
        'deficit' : number,
        'cycle_reserve' : number,
      },
      'engineState' : {
        'harmonic_cycl' : number,
        'total_cycl' : number,
        'total_conversions' : bigint,
        'prime_cycl' : number,
        'fibonacci_cycl' : number,
      },
      'coreState' : {
        'field' : number,
        'total' : number,
        'resonance' : number,
        'coherence' : number,
        'beats' : bigint,
        'genesis' : number,
      },
    }
  >,
  /**
   * / Last N accepted delta records, newest-first (max 144).
   */
  'getDeltaRecords' : ActorMethod<[bigint], Array<DeltaRecord>>,
  'getDoctorReport' : ActorMethod<
    [],
    {
      'cc' : bigint,
      'ds' : number,
      'rd' : number,
      'sh' : bigint,
      'scan' : bigint,
    }
  >,
  /**
   * / Compute doctrine distance for any artifact frequency.
   * / 1.0 = perfectly aligned with 528 Hz founding vibration.
   */
  'getDoctrineDistance' : ActorMethod<[number], number>,
  /**
   * / Current DogonSubstrateReading field state — the organism's proprioception.
   */
  'getDogonFieldState' : ActorMethod<[], number>,
  /**
   * / Which signal source is currently driving the organism's cognition.
   */
  'getDominantSignalSource' : ActorMethod<[], string>,
  /**
   * / 64-sample ECG waveform — live P-QRS-T morphology for display
   */
  'getECGBuffer' : ActorMethod<[], Array<number>>,
  'getExperimentArtifacts' : ActorMethod<[], Array<ExperimentChamberArtifact>>,
  'getFearMissionState' : ActorMethod<
    [],
    {
      'streakCounter' : bigint,
      'missionPersistence' : number,
      'phaseResetCount' : bigint,
      'beatCount' : bigint,
      'surrenderFloor' : number,
      'conqueredFearCount' : bigint,
      'hpaAxisState' : number,
      'groundedScore' : number,
      'adrenalBlastActive' : boolean,
      'amygdalaActivation' : number,
      'valBasinCrossCount' : bigint,
      'fightFlightFreeze' : bigint,
      'bhCouplingCoherence' : number,
      'kuramotoR' : number,
      'missionLockActive' : boolean,
      'fearVelocity' : number,
      'darkNightCount' : bigint,
      'darkNightActive' : boolean,
      'courageScore' : number,
      'fearLevel' : number,
    }
  >,
  /**
   * / Full financial state snapshot: balance in e8s + ICP, total entries,
   * / best artifact value, mean quality, catalog integrity hash.
   */
  'getFinancialState' : ActorMethod<[], FinancialState>,
  /**
   * / Founder attribution — "Alfredo Medina Hernandez — Dallas TX 2026"
   */
  'getFounderAttribution' : ActorMethod<[], string>,
  /**
   * / Full financial state + ledger integrity verification.
   * / Returns all financial sovereignty fields for the frontend LAWS/Treasury display.
   */
  'getFullFinancialState' : ActorMethod<
    [],
    {
      'totalArtifacts' : bigint,
      'ledgerIntegrityHash' : string,
      'totalE8s' : bigint,
      'totalICP' : number,
      'lastEntryCount' : bigint,
      'genesisRecorded' : boolean,
      'totalSacesiProofs' : bigint,
      'founderAttribution' : string,
      'financialState' : FinancialState,
    }
  >,
  /**
   * / Mean genesis alignment across all legacy entries.
   */
  'getGenesisAlignmentMean' : ActorMethod<[], number>,
  /**
   * / PHI-weighted genesis alignment score from doctrine + coherence inputs.
   */
  'getGenesisAlignmentScore' : ActorMethod<[number, number], number>,
  /**
   * / Return the sealed genesis record. Null before first activation.
   */
  'getGenesisRecord' : ActorMethod<[], [] | [GenesisRecord]>,
  /**
   * / Current geometry state snapshot: tesseract rotation, Hopf fiber angles,
   * / Penrose tile distribution, E8 symmetry score.
   */
  'getGeometryState' : ActorMethod<[], GeometryState>,
  /**
   * / Full HRV diagnostic — SDNN, RMSSD, LF/HF balance, health score
   */
  'getHRVState' : ActorMethod<
    [],
    { 'lfhf' : number, 'sdnn' : number, 'rmssd' : number, 'health' : number }
  >,
  /**
   * / Current heart rate in BPM (60000 / currentRateMs)
   */
  'getHeartRateBPM' : ActorMethod<[], number>,
  'getHeartState' : ActorMethod<
    [],
    {
      'd' : number,
      'f' : number,
      'h' : number,
      'm' : number,
      'n' : number,
      'v' : number,
      'bpm' : number,
      'fired' : boolean,
      'avDelayMs' : number,
      'hrv_rmssd' : number,
      'beatCount' : bigint,
      'currentRateMs' : number,
      'cardiacOutput' : number,
      'hrv_sdnn' : number,
    }
  >,
  'getHeartbeatInterval' : ActorMethod<[], bigint>,
  'getHiveMindState' : ActorMethod<[], HiveMindState>,
  /**
   * / Get the most recent crown alerts — AEGIS-style, most recent first.
   * / Fires when any house coherence falls below PHI_INV (0.618).
   */
  'getHouseCrownAlerts' : ActorMethod<[], Array<CrownAlert>>,
  /**
   * / Get the health [0,1] of a specific substrate division within a house.
   * / Healthy range: [PHI_INV, 1.0]. Below PHI_INV triggers crown alert.
   */
  'getHouseDivisionHealth' : ActorMethod<[HouseId, Division], number>,
  /**
   * / Get the live state of a specific house by HouseId.
   * / Returns the CasaDeMedina crown state or any of the six houses.
   */
  'getHouseState' : ActorMethod<[HouseId], [] | [HouseState]>,
  'getIdentityTraits' : ActorMethod<
    [],
    {
      'discipline' : number,
      'aggression' : number,
      'impulsivity' : number,
      'cautious' : number,
      'cooperative' : number,
    }
  >,
  'getInquisitorPrimeState' : ActorMethod<[], InquisitorPrimeState>,
  'getInquisitorState' : ActorMethod<
    [],
    {
      'hasActiveTask' : boolean,
      'activeTaskPrompt' : string,
      'totalGenerated' : bigint,
      'satisfactionLevel' : number,
      'activeTaskType' : string,
      'hungerLevel' : number,
      'totalSolved' : bigint,
    }
  >,
  /**
   * / Live snapshot of the intake gate — total accepted/rejected, last records, drift score.
   */
  'getIntakeSnapshot' : ActorMethod<[], IntakeSnapshot>,
  'getIoTStatePacket' : ActorMethod<[], IoTStatePacket>,
  /**
   * / Full lab state: all sandboxes, all avatars, lab coherence, active count.
   */
  'getLabState' : ActorMethod<[], LabState>,
  'getLawProofs' : ActorMethod<[], Array<LawProofRecord>>,
  /**
   * / Last 100 ledger entries (most recent first).
   */
  'getLedger' : ActorMethod<[], Array<LedgerEntry>>,
  /**
   * / Returns last N ledger entries for display (most recent first).
   * / N is clamped to 100 maximum per call.
   */
  'getLedgerDisplay' : ActorMethod<[bigint], Array<LedgerEntry>>,
  /**
   * / Look up a specific ledger entry by its unique id.
   */
  'getLedgerEntry' : ActorMethod<[string], [] | [LedgerEntry]>,
  /**
   * / Permanent founder attribution string — sealed on every entry.
   */
  'getLedgerFounderAttribution' : ActorMethod<[], string>,
  /**
   * / Return the full immutable legacy index.
   */
  'getLegacyIndex' : ActorMethod<[], Array<LegacyEntry>>,
  /**
   * / Total artifacts recorded in the legacy index.
   */
  'getLegacyIndexLength' : ActorMethod<[], bigint>,
  'getMemoryTempleState' : ActorMethod<[], MemoryTempleState>,
  'getMineDepositsNearby' : ActorMethod<
    [number, number, number],
    Array<MineralDeposit>
  >,
  'getMiningState' : ActorMethod<
    [],
    {
      'ant' : number,
      'drt' : number,
      'hbt' : number,
      'mtc' : number,
      'mth' : number,
      'oms' : number,
      'streak' : bigint,
      'total' : bigint,
      'mult' : number,
      'seed' : number,
      'docHash' : number,
      'lastBeat' : bigint,
    }
  >,
  /**
   * / Returns a single model's promotion record by id.
   */
  'getModelPromotionState' : ActorMethod<[string], [] | [ModelPromotionRecord]>,
  /**
   * / All 43 sovereign model accumulated weights.
   */
  'getModelWeights' : ActorMethod<[], Array<number>>,
  'getMonologueStream' : ActorMethod<[], Array<MonologueEntry>>,
  /**
   * / Full neural cord state — 96-node HH network, brain regions, Third Brain
   * / spike rate, oscillation band, and cross-node coherence
   */
  'getNeuralCordState' : ActorMethod<
    [],
    {
      'dominantNeurotransmitter' : string,
      'node_count' : bigint,
      'spike_rate_hz' : number,
      'thirdBrain_autonomic' : number,
      'oscillationBand' : string,
      'currentTime' : number,
      'neural_coherence' : number,
      'hebbian_mean_weight' : number,
      'thirdBrain_serotonin' : number,
      'thirdBrain_coherence' : number,
    }
  >,
  /**
   * / Real-time LIF hub potentials — Thalamus, Amygdala, Hippocampus, dACC, LC-NE.
   * / Returns current membrane potentials in [0, PHI^-1] range.
   * / Values reset to 0 on threshold crossing (fire-and-reset).
   */
  'getNeuromorphicHubState' : ActorMethod<
    [],
    {
      'thalamus' : number,
      'dacc' : number,
      'lcne' : number,
      'hippocampus' : number,
      'amygdala' : number,
    }
  >,
  'getNunHekaAnkhState' : ActorMethod<
    [],
    {
      'hekaWaveAmp' : number,
      'atumCount' : bigint,
      'ankhExpressionCoherence' : number,
      'ankhFullLock' : boolean,
      'nunCharge' : number,
      'ankhEconomicCoherence' : number,
      'ankhPerceptionCoherence' : number,
      'ankhCognitiveCoherence' : number,
      'hekaEvents' : bigint,
      'ankhLockCount' : bigint,
      'nunResting' : boolean,
    }
  >,
  'getOperatorSnapshot' : ActorMethod<[], OperatorSnapshot>,
  'getPharmaExperimentHistory' : ActorMethod<[], Array<ExperimentHistoryEntry>>,
  'getPharmaHypotheses' : ActorMethod<[], Array<HypothesisRecord>>,
  /**
   * / Returns all 43 ModelPromotionRecords — frontend promotion dashboard.
   */
  'getPromotionSnapshot' : ActorMethod<[], Array<ModelPromotionRecord>>,
  /**
   * / M0/M1/M2 counts and total proof bundle count.
   */
  'getPromotionSummary' : ActorMethod<[], PromotionSummary>,
  'getPublishableReports' : ActorMethod<[], Array<GeneratedReport>>,
  'getRLEngineState' : ActorMethod<
    [],
    {
      'alpha' : number,
      'rewardHistory' : Array<number>,
      'lawOutcome' : Array<number>,
      'pathwayBoost' : number,
      'gamma' : number,
      'totalReward' : number,
      'lastReward' : number,
      'qValues' : Array<number>,
    }
  >,
  /**
   * / How many artifacts are queued for re-ingestion.
   */
  'getReingestionQueueDepth' : ActorMethod<[], bigint>,
  /**
   * / Re-ingestion stats: sealed count, reingested count, world model weight, field state.
   */
  'getReingestionStats' : ActorMethod<[], PipelineStats>,
  /**
   * / Last N rejected intelligence records with proof, newest-first (max 89).
   */
  'getRejectionLog' : ActorMethod<[bigint], Array<RejectionRecord>>,
  'getReportEngineState' : ActorMethod<[], ReportEngineState>,
  /**
   * / Ring 15 closure state — production measured against founding vibration.
   */
  'getRing15Status' : ActorMethod<[], Ring15State>,
  /**
   * / Get which houses a given SDK organism inhabits.
   * / Returns a list of HouseIds — SDK organisms live across multiple houses.
   */
  'getSDKOrganismHouses' : ActorMethod<[SDKOrganism], Array<HouseId>>,
  /**
   * / Current saturation damping state — enabled flag + live saturated node count.
   */
  'getSaturationDampingState' : ActorMethod<
    [],
    { 'saturatedCount' : bigint, 'enabled' : boolean }
  >,
  /**
   * / Returns the multi-canister sovereign architecture identifier.
   * / CACHE BUST: second new exported symbol, different name, same guarantee.
   */
  'getSovereignArchitecture' : ActorMethod<[], string>,
  /**
   * / Current spike rate in Hz across all 96 neural nodes
   */
  'getSpikeRateHz' : ActorMethod<[], number>,
  'getSubstrateMineState' : ActorMethod<[], SubstrateMineState>,
  'getSubstrateVersion' : ActorMethod<[], string>,
  /**
   * / Third Brain field coherence — enteric sovereignty layer output
   * / Always on. Cannot be overridden. Holds 7 cosmological standing waves.
   */
  'getThirdBrainCoherence' : ActorMethod<[], number>,
  /**
   * / Third Brain 9 cosmological standing wave amplitudes.
   * / These are the permanent standing waves — frequencies never change,
   * / only amplitudes modulate with Kuramoto coherence.
   * / Waves: [Schumann1, Schumann2, Schumann3, Tzolkin, Haab, PHI×Sch, GoldenAngle×Sch, Solfeggio528, Nova432]
   */
  'getThirdBrainWaves' : ActorMethod<[], Array<number>>,
  /**
   * / Total balance in e8s (1 ICP = 100_000_000 e8s).
   */
  'getTotalBalanceE8s' : ActorMethod<[], bigint>,
  /**
   * / The live world model — all 13+ signal sources unified.
   * / Rebuilt every 873ms heartbeat. The organism knowing itself.
   */
  'getWorldModel' : ActorMethod<[], WorldModel>,
  /**
   * / Initialize a sovereign avatar brain chip (Ring 8 sub-instance).
   * / Each avatar gets 6 Kuramoto nodes with golden-angle phase spacing.
   * / avatarId must be in [0, 7]. Returns false if out of range.
   */
  'initAvatarBrain' : ActorMethod<[bigint], boolean>,
  'injectPerception' : ActorMethod<[number, number, number, number], undefined>,
  /**
   * / Submit new intelligence for intake. Returns (accepted, record_id).
   * / Accepted truths generate a DeltaRecord with SACESI proof.
   * / Rejected truths generate a RejectionRecord with violation proof.
   */
  'intakeIntelligence' : ActorMethod<
    [string, bigint, number],
    [boolean, string]
  >,
  /**
   * / True if a user message was processed this beat.
   */
  'isCognitionUserPresent' : ActorMethod<[], boolean>,
  /**
   * / True if the genesis ledger entry (10 ICP) has been recorded. (alias)
   */
  'isGenesisRecorded' : ActorMethod<[], boolean>,
  /**
   * / True after the founding moment is permanently sealed.
   */
  'isGenesisSealed' : ActorMethod<[], boolean>,
  /**
   * / True if the genesis ledger entry (10 ICP) has been recorded.
   */
  'isLedgerGenesisRecorded' : ActorMethod<[], boolean>,
  'manualMineDeposit' : ActorMethod<
    [string, bigint],
    [] | [{ 'neurotransmitter' : string, 'delta' : number }]
  >,
  'markPuzzleSolved' : ActorMethod<[bigint, bigint], number>,
  /**
   * / Current E8 alignment / octonion field strength [0,1].
   */
  'octonionFieldStrength' : ActorMethod<[], number>,
  'presenceCharge' : ActorMethod<[], undefined>,
  /**
   * / Quaternion coupling strength between two nodes [0,1].
   */
  'quaternionCoupling' : ActorMethod<[bigint, bigint], number>,
  /**
   * / Record a legacy entry — append-only, never deleted.
   * / Called by every sealing function before it returns.
   */
  'recordLegacyEntry' : ActorMethod<[LegacyEntry], undefined>,
  /**
   * / Records a proof bundle for a specific model.
   */
  'recordModelProof' : ActorMethod<
    [string, string, number, bigint, string],
    undefined
  >,
  /**
   * / Requests promotion — adreGateHash must come from the current ADRE deliberation cycle.
   */
  'requestModelPromotion' : ActorMethod<[string, string], [boolean, string]>,
  'runCombination' : ActorMethod<
    [string, string, number, number, number],
    CombinationResult
  >,
  'runControlledSession' : ActorMethod<
    [string, number, bigint],
    ControlledSessionResult
  >,
  'runDoseResponse' : ActorMethod<
    [string, Array<number>, number, number, number],
    DoseResponseResult
  >,
  'runLongitudinal' : ActorMethod<[string, bigint, number], LongitudinalResult>,
  'runReceptorMapping' : ActorMethod<
    [string, Array<[string, number]>],
    ReceptorMappingResult
  >,
  /**
   * / Run one simulation step on a sandbox.
   * / emergenceScore = kuramotoR × fractalDimension × phiCoupling × couplingCoeff / 3.0
   */
  'runSandboxStep' : ActorMethod<
    [bigint],
    { 'ok' : Sandbox } |
      { 'err' : string }
  >,
  /**
   * / Seal a new artifact into the re-ingestion pipeline.
   * / Scoring: PHI-weighted composite across 6 quality dimensions.
   * / SACESI proof generated via FNV-1a. Returns the sealed artifact.
   */
  'sealArtifact' : ActorMethod<
    [string, number, number, number, number, number, number],
    SealedArtifact
  >,
  /**
   * / Seal an experiment as a sovereign artifact.
   * / Every seal is a financial event on the SACESI proof chain.
   */
  'sealExperiment' : ActorMethod<
    [bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'sealVirtualExperimentArtifact' : ActorMethod<
    [string, string, string, number, number, bigint],
    ExperimentChamberArtifact
  >,
  'setCreatorPrincipal' : ActorMethod<[], undefined>,
  'setTreasurySignals' : ActorMethod<[number, number, number], undefined>,
  /**
   * / Bulk heartbeat proof submission — also callable externally for test harnesses.
   */
  'submitHeartbeatProofs' : ActorMethod<[bigint, number, bigint], undefined>,
  /**
   * / Process a user entry through the 5-pass cognition loop.
   * / Updates world model with user signal (weight = 1.0, highest).
   */
  'submitUserEntry' : ActorMethod<[string], CognitionState>,
  /**
   * / Toggle homeostatic tidal return (saturation dampening) on/off.
   */
  'toggleSaturationDamping' : ActorMethod<[boolean], undefined>,
  'triggerPuzzleGeneration' : ActorMethod<[bigint], [] | [CognitivePuzzle]>,
  'updateAvatarMining' : ActorMethod<[string, string, number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];